[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rs-archaeology-helper"
description = "Helper tool for the RuneScape archaeology skill."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT License"}
authors = [
    {name = "Peter Schaedler", email = "pwschaedler@gmail.com"}
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "yapf",
    "mypy",
    "pylint"
]
test = [
    "pytest",
    "pytest-cov"
]

[project.scripts]
rs-archeology-helper = "rs_arch.cli:cli"

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = "--cov"





#------------------------------------------------------------------------


# authors = ["Peter Schaedler <pwschaedler@gmail.com>"]
# packages = [
#     { include = "rs_arch" }
# ]

# [tool.poetry.dev-dependencies]
# mypy = "^0.931"
# pylint = "^2.12.2"
# black = "^21.12b0"
